In [2]:
## 1)Student Marks
import numpy as np

marks = [78, 85, 91, 67, 88]

marks_arr = np.array(marks)

print("Array:", marks_arr)
print("Data Type:", marks_arr.dtype)
print("Shape:", marks_arr.shape)

Array: [78 85 91 67 88]
Data Type: int64
Shape: (5,)


In [3]:
## 2)Shopping Prices
import numpy as np

prices = [120, 450, 780, 220, 560]

prices_arr = np.array(prices)

print("Array:", prices_arr)
print("Dimensions:", prices_arr.ndim)
print("Size:", prices_arr.size)

Array: [120 450 780 220 560]
Dimensions: 1
Size: 5


In [4]:
## 3)Game Scores
import numpy as np

scores = np.array([45, 67, 89, 56, 78, 90, 88, 76, 95, 82])

print("Scores:", scores)
print("Shape:", scores.shape)
print("Size:", scores.size)
print("Data Type:", scores.dtype)
print("Dimensions:", scores.ndim)

Scores: [45 67 89 56 78 90 88 76 95 82]
Shape: (10,)
Size: 10
Data Type: int64
Dimensions: 1


In [5]:
## 4)Bonus Calculation
import numpy as np

salary = [25000, 30000, 45000, 28000]

# Python List
updated_salary_list = []
for s in salary:
    updated_salary_list.append(s + 5000)

print("Updated Salary using Python List:")
print(updated_salary_list)

# NumPy Array
salary_arr = np.array(salary)
updated_salary_arr = salary_arr + 5000

print("\nUpdated Salary using NumPy:")
print(updated_salary_arr)

Updated Salary using Python List:
[30000, 35000, 50000, 33000]

Updated Salary using NumPy:
[30000 35000 50000 33000]


In [6]:
## 5)Student Marks Increase
import numpy as np

marks = [60, 75, 80, 90, 65]

# Python List
new_marks = []
for m in marks:
    new_marks.append(m + 5)

print("Python List:")
print(new_marks)

# NumPy Array
marks_arr = np.array(marks)
updated_marks = marks_arr + 5

print("\nNumPy Array:")
print(updated_marks)

Python List:
[65, 80, 85, 95, 70]

NumPy Array:
[65 80 85 95 70]


In [7]:
## 6)Performance Observation
import numpy as np
import time

# Python List
py_list = list(range(100000))

start = time.time()
result_list = [x + 10 for x in py_list]
end = time.time()

print("Python List Time:", end - start)

# NumPy Array
np_array = np.arange(100000)

start = time.time()
result_array = np_array + 10
end = time.time()

print("NumPy Array Time:", end - start)

Python List Time: 0.0036640167236328125
NumPy Array Time: 0.0003070831298828125


In [8]:
## 7)import numpy as np

# Python List
prices_list = [20, 35, 50, 40]

print("Python List * 2:")
print(prices_list * 2)

# NumPy Array
prices_array = np.array([20, 35, 50, 40])

print("\nNumPy Array * 2:")
print(prices_array * 2)
import numpy as np

# Python List
prices_list = [20, 35, 50, 40]

print("Python List * 2:")
print(prices_list * 2)

# NumPy Array
prices_array = np.array([20, 35, 50, 40])

print("\nNumPy Array * 2:")
print(prices_array * 2)

Python List * 2:
[20, 35, 50, 40, 20, 35, 50, 40]

NumPy Array * 2:
[ 40  70 100  80]
Python List * 2:
[20, 35, 50, 40, 20, 35, 50, 40]

NumPy Array * 2:
[ 40  70 100  80]


In [9]:
## 8)Warehouse Stock
import numpy as np

# Python List
stock_list = [100, 200, 150, 300]

print("Python List * 2:")
print(stock_list * 2)

# NumPy Array
stock_array = np.array([100, 200, 150, 300])

print("\nNumPy Array * 2:")
print(stock_array * 2)

Python List * 2:
[100, 200, 150, 300, 100, 200, 150, 300]

NumPy Array * 2:
[200 400 300 600]


In [10]:
## 9)Monthly Expenses
import numpy as np

expenses = [12000, 15000, 10000, 18000]

# Python List
total_list = sum(expenses)
print("Total using Python List:", total_list)

# NumPy Array
expenses_array = np.array(expenses)
total_array = np.sum(expenses_array)

print("Total using NumPy:", total_array)

Total using Python List: 55000
Total using NumPy: 55000


In [11]:
## 10)Student Marks (Indexing)
import numpy as np

marks = np.array([55, 65, 75, 85, 95])

print("Marks:", marks)
print("First Element:", marks[0])
print("Last Element:", marks[-1])
print("Third Element:", marks[2])

Marks: [55 65 75 85 95]
First Element: 55
Last Element: 95
Third Element: 75


In [12]:
## 11)Mobile Sales (Slicing)
import numpy as np

sales = np.array([120, 130, 140, 150, 160, 170])

print("Sales:", sales)
print("First Three Values:", sales[:3])
print("Last Two Values:", sales[-2:])
print("Middle Values:", sales[2:4])

Sales: [120 130 140 150 160 170]
First Three Values: [120 130 140]
Last Two Values: [160 170]
Middle Values: [140 150]


In [13]:
## 12)Matrix Game
import numpy as np

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Matrix:")
print(matrix)

print("First Row:", matrix[0])
print("Second Column:", matrix[:, 1])
print("Last Row:", matrix[2])

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
First Row: [1 2 3]
Second Column: [2 5 8]
Last Row: [7 8 9]


In [14]:
## 13)Passed Students (Boolean Indexing)
import numpy as np

marks = np.array([35, 55, 72, 89, 40, 91])

passed_students = marks[marks >= 40]

print("Marks:", marks)
print("Passed Students:", passed_students)

Marks: [35 55 72 89 40 91]
Passed Students: [55 72 89 40 91]


In [15]:
## 14)High Salaries
import numpy as np

salary = np.array([35000, 48000, 52000, 65000, 45000, 70000])

high_salary = salary[salary > 50000]

print("Salaries:", salary)
print("Employees earning more than ₹50,000:")
print(high_salary)

Salaries: [35000 48000 52000 65000 45000 70000]
Employees earning more than ₹50,000:
[52000 65000 70000]


In [16]:
## 15)Temperature Report
import numpy as np

temperature = np.array([25, 28, 31, 35, 29, 33, 27])

high_temperature = temperature[temperature > 30]

print("Temperatures:", temperature)
print("Temperatures above 30°C:")
print(high_temperature)

Temperatures: [25 28 31 35 29 33 27]
Temperatures above 30°C:
[31 35 33]


In [17]:
## 16)Movie Ratings (Fancy Indexing)
import numpy as np

ratings = np.array([2, 5, 4, 3, 5, 1])

selected_ratings = ratings[[0, 2, 5]]

print("Ratings:", ratings)
print("Selected Ratings:", selected_ratings)

Ratings: [2 5 4 3 5 1]
Selected Ratings: [2 4 1]


In [18]:
## 17)Library Books
import numpy as np

books = np.array([
    "Python",
    "Java",
    "C",
    "C++",
    "SQL",
    "AI"
])

selected_books = books[[1, 3, 4]]

print("Books:", books)
print("Selected Books:", selected_books)

Books: ['Python' 'Java' 'C' 'C++' 'SQL' 'AI']
Selected Books: ['Java' 'C++' 'SQL']


In [19]:
## 18)Cricket Scores
import numpy as np

scores = np.array([45, 52, 68, 74, 89, 91, 105])

selected_scores = scores[[0, 3, 6]]

print("Scores:", scores)
print("Selected Scores:", selected_scores)

Scores: [ 45  52  68  74  89  91 105]
Selected Scores: [ 45  74 105]


In [20]:
## 19)Arithmetic Operations (UFuncs)
import numpy as np

arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([2, 4, 5, 8])

print("Array 1:", arr1)
print("Array 2:", arr2)

print("Addition:", np.add(arr1, arr2))
print("Subtraction:", np.subtract(arr1, arr2))
print("Multiplication:", np.multiply(arr1, arr2))
print("Division:", np.divide(arr1, arr2))

Array 1: [10 20 30 40]
Array 2: [2 4 5 8]
Addition: [12 24 35 48]
Subtraction: [ 8 16 25 32]
Multiplication: [ 20  80 150 320]
Division: [5. 5. 6. 5.]


In [21]:
## 20)Square Roots
import numpy as np

arr = np.array([1, 4, 9, 16, 25])

print("Array:", arr)
print("Square Root:", np.sqrt(arr))
print("Square:", np.square(arr))
print("Exponential:", np.exp(arr))

Array: [ 1  4  9 16 25]
Square Root: [1. 2. 3. 4. 5.]
Square: [  1  16  81 256 625]
Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]


In [22]:
## 21)Trigonometry
import numpy as np

angles = np.array([0, 30, 45, 60, 90])

# Convert degrees to radians
radians = np.radians(angles)

print("Angles:", angles)

print("Sin:", np.sin(radians))
print("Cos:", np.cos(radians))
print("Tan:", np.tan(radians))

Angles: [ 0 30 45 60 90]
Sin: [0.         0.5        0.70710678 0.8660254  1.        ]
Cos: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
Tan: [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [23]:
## 22)tudent Analysis (Aggregation Functions)
import numpy as np

marks = np.array([78, 85, 91, 67, 88])

print("Marks:", marks)
print("Mean:", np.mean(marks))
print("Median:", np.median(marks))
print("Sum:", np.sum(marks))
print("Minimum:", np.min(marks))
print("Maximum:", np.max(marks))

Marks: [78 85 91 67 88]
Mean: 81.8
Median: 85.0
Sum: 409
Minimum: 67
Maximum: 91


In [24]:
## 23)Factory Production
import numpy as np

production = np.array([120, 150, 130, 170, 160, 180])

print("Production:", production)
print("Standard Deviation:", np.std(production))
print("Variance:", np.var(production))
print("Average Production:", np.mean(production))

Production: [120 150 130 170 160 180]
Standard Deviation: 21.147629234082533
Variance: 447.2222222222222
Average Production: 151.66666666666666


In [25]:
## 24)Sales Analysis
import numpy as np

sales = np.array([25000, 27000, 30000, 28000, 35000])

print("Sales:", sales)
print("Sum:", np.sum(sales))
print("Mean:", np.mean(sales))
print("Maximum:", np.max(sales))
print("Minimum:", np.min(sales))
print("Standard Deviation:", np.std(sales))
print("Variance:", np.var(sales))

Sales: [25000 27000 30000 28000 35000]
Sum: 145000
Mean: 29000.0
Maximum: 35000
Minimum: 25000
Standard Deviation: 3405.87727318528
Variance: 11600000.0


In [26]:
## 25)Top Scorer
import numpy as np

marks = np.array([78, 85, 91, 67, 88])

print("Marks:", marks)

print("Index of Maximum Value:", np.argmax(marks))
print("Index of Minimum Value:", np.argmin(marks))

Marks: [78 85 91 67 88]
Index of Maximum Value: 2
Index of Minimum Value: 3


In [27]:
## 26)Daily Savings
import numpy as np

savings = np.array([100, 200, 300, 400])

print("Savings:", savings)

print("Cumulative Sum:", np.cumsum(savings))
print("Cumulative Product:", np.cumprod(savings))

Savings: [100 200 300 400]
Cumulative Sum: [ 100  300  600 1000]
Cumulative Product: [       100      20000    6000000 2400000000]


In [28]:
## 27)Health Report
import numpy as np

health = np.array([True, True, False, True])

print("Health Status:", health)

print("All values are True:", np.all(health))
print("Any value is True:", np.any(health))

Health Status: [ True  True False  True]
All values are True: False
Any value is True: True
